# Generated by Django 4.1.7 on 2023-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0002_remove_maintainance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainance',
            name='status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
    ]
