# Generated by Django 4.1.7 on 2023-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0020_eventviewdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/default.pic.png', upload_to='media/upload'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
