# Generated by Django 4.1.7 on 2023-03-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0021_alter_chairman_pic_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('duedate', models.DateField(max_length=30)),
                ('status', models.CharField(default='PANDING', max_length=30)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairmanapp.societymember')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairmanapp.user')),
            ],
        ),
    ]
